# Generated by Django 6.0.3 on 2026-04-13 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
